/*
 * Micro service
 * Micro service to book a visit
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.microbooking.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.math.BigDecimal;
/**
 * BookingInfo
 */

public class BookingInfo {

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("cost")
  private BigDecimal cost = null;

  @JsonProperty("bvr")
  BookVisitRequest bvr = null;

  public BookVisitRequest getBvr() {
    return this.bvr;
  }

  public void setBvr(BookVisitRequest bcr) {
    this.bvr = bcr;
  }

  public BookingInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/


  public String getId() { return id; }

  public void setId(String id) {
    this.id = id;
  }

  public BookingInfo cost(BigDecimal cost) {
    this.cost = cost;
    return this;
  }

   /**
   * Get cost
   * @return cost
  **/

  public BigDecimal getCost() {
    return cost;
  }

  public void setCost(BigDecimal cost) {
    this.cost = cost;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BookingInfo bookingInfo = (BookingInfo) o;
    return Objects.equals(this.id, bookingInfo.id) &&
        Objects.equals(this.cost, bookingInfo.cost);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, cost);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BookingInfo {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
