/*
 * Micro service
 * Micro service to book a visit
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.microbooking.model;

import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Date;
/**
 * Visit
 */

public class Visit {
  @JsonProperty("dateStart")
  private Date dateStart = null;

  @JsonProperty("dateStop")
  private Date dateStop = null;

  public Visit dateStart(Date dateStart) {
    this.dateStart = dateStart;
    return this;
  }

   /**
   * Get dateStart
   * @return dateStart
  **/
  public Date getDateStart() {
    return dateStart;
  }

  public void setDateStart(Date dateStart) {
    this.dateStart = dateStart;
  }

  public Visit dateStop(Date dateStop) {
    this.dateStop = dateStop;
    return this;
  }

   /**
   * Get dateStop
   * @return dateStop
  **/
  public Date getDateStop() {
    return dateStop;
  }

  public void setDateStop(Date dateStop) {
    this.dateStop = dateStop;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Visit visit = (Visit) o;
    return Objects.equals(this.dateStart, visit.dateStart) &&
        Objects.equals(this.dateStop, visit.dateStop);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateStart, dateStop);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Visit {\n");
    
    sb.append("    dateStart: ").append(toIndentedString(dateStart)).append("\n");
    sb.append("    dateStop: ").append(toIndentedString(dateStop)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static String getDayOfWeek(Date date) {
    // Konwersja Date na LocalDate
    LocalDate localDate = date.toInstant()
            .atZone(ZoneId.systemDefault())
            .toLocalDate();

    // Pobranie dnia tygodnia
    DayOfWeek dayOfWeek = localDate.getDayOfWeek();

    // Zwrócenie pełnej nazwy dnia tygodnia
    return dayOfWeek.toString(); // Zwraca np. "MONDAY"
  }

  public static boolean isSameDayAndValidTime(Date dateStart, Date dateStop) {
    if (dateStart == null || dateStop == null) {
      return false;
    }

    LocalDateTime start = dateStart.toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
    LocalDateTime stop = dateStop.toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();

    boolean sameDay = start.toLocalDate().equals(stop.toLocalDate());

    boolean validTime = stop.isAfter(start);

    return sameDay && validTime;
  }

}
